FROM ubuntu:18.04

RUN apk add --update openssh

RUN apt update && apt install software-properties-common ssh -y

USER deploy
WORKDIR /home/deploy

RUN mkdir ~/.ssh
RUN mkdir ~/keys

RUN echo "Host * \n StrictHostKeyChecking no" > ~/.ssh/config
